"""empty message

Revision ID: 3c7676b9ffc4
Revises: 3f610a70d491
Create Date: 2026-03-20 22:20:55.946213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7676b9ffc4'
down_revision = '3f610a70d491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_reviews_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_num', sa.Integer(), nullable=False))
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('rating_nдum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_nдum', sa.INTEGER(), nullable=False))
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('rating_num')

    op.drop_table('reviews')
    # ### end Alembic commands ###
