"""Make background_image_id nullable

Revision ID: 3f610a70d491
Revises: 82d4de5e1559
Create Date: 2026-03-20 21:46:17.671157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f610a70d491'
down_revision = '82d4de5e1559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_nдum', sa.Integer(), nullable=False))
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('rating_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_num', sa.INTEGER(), nullable=False))
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('rating_nдum')

    # ### end Alembic commands ###
